server:
  port: 8761

eureka:
  client:
    service-url:
      # 服务中心地址
      defaultZone: http://127.0.0.1:8761/eureka
    # 关闭立即注册，待服务器启动完成后再注册
    fetch-registry: false
    # 使当前应用不注册到服务中心
    register-with-eureka: false

spring:
  application:
    name: EUREKASERVER
